name = "otp-proxy"
main = "index.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "OTP_STORE"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_YOUR_KV_PREVIEW_ID"

[vars]
ALLOWED_ORIGIN = "https://sunny-kathuria.github.io"
